version: "3.9"
services:
  web:
    environment:
      DB_CONNECTION_STR: "postgresql://postgres:example@postgres:6000/postgres"
    build: .
    ports:
      - "5000:5000"
  db:
    image: "postgres"
    hostname: "postgres"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "6000:5432"