"""four

Revision ID: 49e90e8ac770
Revises: 90cd175ed630
Create Date: 2022-09-21 17:53:13.740335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e90e8ac770'
down_revision = '90cd175ed630'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
