"""thirt

Revision ID: 90cd175ed630
Revises: b5ca77edf5f8
Create Date: 2022-09-21 17:50:47.225856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cd175ed630'
down_revision = 'b5ca77edf5f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
