"""second

Revision ID: b5ca77edf5f8
Revises: 64cb431832cc
Create Date: 2022-09-17 10:41:28.517350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ca77edf5f8'
down_revision = '64cb431832cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaction', sa.Column('id_operation', sa.TEXT(), nullable=False))
    op.add_column('Transaction', sa.Column('status_operation', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transaction', 'status_operation')
    op.drop_column('Transaction', 'id_operation')
    # ### end Alembic commands ###
