"""empty message

Revision ID: 8d1591397059
Revises: 8d7e352a4676
Create Date: 2022-09-06 17:03:17.542854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1591397059'
down_revision = '8d7e352a4676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('date_open', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'date_open')
    # ### end Alembic commands ###
