"""empty message

Revision ID: 8d7e352a4676
Revises: 
Create Date: 2022-09-06 16:26:59.011659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7e352a4676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('id_currency', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id_currency', sa.INTEGER(), nullable=False),
    sa.Column('name_currency', sa.TEXT(), nullable=False),
    sa.Column('cost_in_USD', sa.REAL(), nullable=False),
    sa.Column('available_quantity', sa.REAL(), nullable=False),
    sa.Column('pricing_date', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id_currency')
    )
    op.create_table('deposit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('opening_date', sa.TEXT(), nullable=False),
    sa.Column('closing_date', sa.TEXT(), nullable=False),
    sa.Column('id_currency', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.REAL(), nullable=False),
    sa.Column('interest_rate', sa.INTEGER(), nullable=False),
    sa.Column('storage_conditions', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_currency', sa.INTEGER(), nullable=False),
    sa.Column('user_rating', sa.REAL(), nullable=False),
    sa.Column('review_client', sa.TEXT(), nullable=False),
    sa.Column('date_review', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type_operation', sa.TEXT(), nullable=False),
    sa.Column('id_currency_output', sa.INTEGER(), nullable=False),
    sa.Column('id_currency_input', sa.INTEGER(), nullable=False),
    sa.Column('count_currency_spent', sa.REAL(), nullable=False),
    sa.Column('count_currency_received', sa.REAL(), nullable=False),
    sa.Column('commission', sa.REAL(), nullable=False),
    sa.Column('id_account_output', sa.INTEGER(), nullable=False),
    sa.Column('id_account_input', sa.INTEGER(), nullable=False),
    sa.Column('date_operation', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transactions')
    op.drop_table('review')
    op.drop_table('deposit')
    op.drop_table('currency')
    op.drop_table('account')
    # ### end Alembic commands ###
